module.exports = {
    swiftTypeMap: {
        "String": "String",
        "Integer": "Int",
        "Boolean": "Bool",
        "Double": "Double",
        "Optional<String>": "String?",
        "Optional<Integer>": "Int?",
        "Optional<Boolean>": "Bool?",
        "Optional<Double>": "Double?",
        "Array<String>": "[String]",
        "Array<Integer>": "[Int]",
        "Array<Boolean>": "[Bool]",
        "Array<Double>": "[Double]",
        "Array<Optional<String>>": "[String?]",
        "Array<Optional<Integer>>": "[Int?]",
        "Array<Optional<Boolean>>": "[Bool?]",
        "Array<Optional<Double>>": "[Double?]",
        "Dictionary<String, Any>": "[String: Any]"
    },
    kotlinTypeMap: {
        "String": "String",
        "Integer": "Int",
        "Boolean": "Boolean",
        "Double": "Double",
        "Optional<String>": "String?",
        "Optional<Integer>": "Int?",
        "Optional<Boolean>": "Boolean?",
        "Optional<Double>": "Double?",
        "Array<String>": "Array<String>",
        "Array<Integer>": "Array<Int>",
        "Array<Boolean>": "Array<Boolean>",
        "Array<Double>": "Array<Double>",
        "Array<Optional<String>>": "Array<String?>",
        "Array<Optional<Integer>>": "Array<Int?>",
        "Array<Optional<Boolean>>": "Array<Boolean?>",
        "Array<Optional<Double>>": "Array<Double?>",
        "Dictionary<String, Any>": "Map<String, Any>"
    },
}