name: Compile and release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          /usr/local/bin/swift-format
          ktfmt.jar
        key: ${{ runner.os }}
    - run: sh compile.sh
    - uses: EndBug/add-and-commit@v7
      with:
        add: '.'
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +%s)"
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ steps.date.outputs.date }}"
        prerelease: true
    
