name: Compile and release

on:
  push:
    branches: [ master ]

jobs:
  gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install and Build 🔧
        run: |
          cd docs
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: docs/build
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          /usr/local/bin/swift-format
          ktfmt.jar
        key: ${{ runner.os }}
    - run: sh compile.sh
    - uses: EndBug/add-and-commit@v7
      with:
        add: '.'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
    
