name: Fetch experiments from Unleash Server
on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - run: npm run fetch-experiments
      env:
        UNLEASH_API_URL: ${{ secrets.UNLEASH_API_URL }}
        UNLEASH_API_KEY: ${{ secrets.UNLEASH_API_KEY }}
    - uses: EndBug/add-and-commit@v7
      with:
        add: '.'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
