name: Sync job
on: [workflow_dispatch]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "15"
      - run: npm install
      - run: node scripts/bigQuerySync.js
        env:
          BQ_DATASET: hanalytics_production_live
          GCLOUD_PROJECT: hedvig-dagobah
          SOURCE_DATASET: hanalytics_production
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      - run: node scripts/bigQueryCopy.js
        env:
          BQ_DATASET: hanalytics_production_live
          GCLOUD_PROJECT: hedvig-dagobah
          DESTINATION_PREFIX: ""
          SOURCE_PREFIX: __sync_table_
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
